export const actionTypes = {
	// GLOBAL
	INITIALIZE_APPLICATION: 'INITIALIZE_APPLICATION',

	// APPLICATION
	UPDATE_TUTORIAL_VIEWED: 'UPDATE_TUTORIAL_VIEWED',
	UPDATE_TUTORIAL_STEP: 'UPDATE_TUTORIAL_STEP',
}
